<?php
/**
 * @file
 * Code for the OpenAtrium Wiki feature.
 */

include_once 'aa_blog.features.inc';


/**
 * Implements hook_theme()
 */
function aa_blog_theme() {
  $displays = array('aa_recent_posts');
  $theme = array();
  foreach ($displays as $display) {
    $key = 'views_view_fields__aa_blog__' . $display;
    $filename = str_replace('_', '-', $key);
    $theme[$key] = array(
      'template'  => $filename,
      'base hook' => 'views_view_fields',
      'preprocess functions' => array(
        'template_preprocess',
        'template_preprocess_views_view_fields',
        'oa_core_preprocess_views_view_fields',
      ),
      'arguments' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'path' => drupal_get_path('module', 'aa_blog') . '/templates',
    );
  }
  return $theme;
}










/**
 * Implements hook_pre_features_rebuild().
 *
 * @see http://drupal.org/node/1549608
 */
function aa_blog_pre_features_rebuild($component) {
  if ($component == 'user_permission') {
    drupal_static_reset('panelizer_entity_plugin_get_handler');
  }
}


/**
 * Implements hook_node_prepare().
 */
function aa_blog_node_prepare($node) {
  if (empty($node->nid) && $node->type == 'aa_blog_page' && module_exists('og_menu_single') && (function_exists('oa_core_get_section_context') && ($section = oa_core_get_section_context())) && ($plid = og_menu_single_get_link_mlid('node', $section))) {
    global $conf;
    // No good way to set default for parent.
    // @see menu_form_node_form_alter().
    $conf['menu_parent_aa_blog_page'] = OG_MENU_SINGLE_MENU_NAME . ':' . $plid;
  }
}

/**
 * Implements hook_strongarm_alter().
 */
function aa_blog_strongarm_alter(&$items) {
  // If workbench_moderation is enabled when aa_blog is enabled, then we enable
  // moderation for aa_blog_pages.
  if (module_exists('workbench_moderation')) {
    $node_options_name = "node_options_aa_blog_page";
    if (isset($items[$node_options_name])) {
      $items[$node_options_name]->value[] = 'moderation';
      sort($items[$node_options_name]->value);
    }
  }

  // Set up space-specific variables.
  if (isset($data['variable_realm_list_og'])) {
    // The assigned to settings.
    if (!in_array('aa_blog_vocab', $data['variable_realm_list_og']->value)) {
      $data['variable_realm_list_og']->value[] = 'aa_blog_vocab';
    }
  }
}

/**
 * Implements hook_modules_implements_alter().
 */
function aa_blog_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'strongarm_alter') {
    // Move aa_blog's implementation to the first one any other modules can
    // override our default easily if they don't want workbenech enabled.
    $group = $implementations['aa_blog'];
    unset($implementations['aa_blog']);
    $implementations = array_merge(array('aa_blog' => $group), $implementations);
  }
  elseif (($hook == 'form_alter') && (isset($implementations['aa_blog']))) {
    $group = $implementations['aa_blog'];
    unset($implementations['aa_blog']);
    $implementations['aa_blog'] = $group;
  }
}

/**
 * Implements hook_modules_installed().
 */
function aa_blog_modules_installed($modules) {
  // If workbench_moderation gets enabled later, then we set the variable
  // manually so the user doesn't have to worry about reverting the feature.
  if (in_array('workbench_moderation', $modules)) {
    $node_options_name = "node_options_aa_blog_page";
    $node_options = variable_get($node_options_name, array());
    $node_options[] = 'moderation';
    sort($node_options);
    variable_set($node_options_name, $node_options);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for aa_blog_page_node_form.
 */
function aa_blog_form_aa_blog_page_node_form_alter(&$form, &$form_state) {
  _oa_core_hide_comment_settings($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function aa_blog_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'aa_blog_page_node_form' && module_exists('oa_files')) {
    $submit_handlers = array(
      'node_form_submit',
      'save_draft_submit',
    );
    foreach (element_children($form['actions']) as $key) {
      if (!empty($form['actions'][$key]['#submit']) && array_intersect($submit_handlers, $form['actions'][$key]['#submit'])) {
        $form['actions'][$key]['#submit'][] = 'aa_blog_redirect_to_view_submit';
      }
    }
  }
}

/**
 * Submission handlers that changes the submit destination to be the view page.
 *
 * With the redirect logic, submitting the form could result in user downloading
 * the file they just uploaded, so this forces them onto the view page instead.
 * Normal destination redirect logic applies still.
 */
function aa_blog_redirect_to_view_submit($form, &$form_state) {
  if (!empty($form_state['nid']) && !empty($form_state['redirect']) && 'node/' .  $form_state['nid'] == $form_state['redirect']) {
    $form_state['redirect'] .= '/view';
  }
}

/**
 * Implements hook_init().
 */
function aa_blog_init() {
  if (module_exists('oa_files') && arg(0) == 'node' && is_numeric(arg(1)) && !arg(2) && ($node = menu_get_object()) && $node->type == 'aa_blog_page') {
    if (($path = aa_blog_node_uri($node)) && $path['path'] != $_GET['q']) {
      node_tag_new($node);
      drupal_goto($path['path']);
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function aa_blog_entity_info_alter(&$info) {
  if (!empty($info['node']['bundles']['aa_blog_page']) && module_exists('oa_files')) {
    $info['node']['bundles']['aa_blog_page']['uri callback'] = 'aa_blog_node_uri';
  }
}

/**
 * Change the URI to the file path for wikis.
 *
 * This only effects places that actually use entity_uri, whic is few but will
 * save a boostrap (no redirect needed) for those places that do.
 */
function aa_blog_node_uri($node) {
  if (!($items = field_get_items('node', $node, 'field_aa_blog_page_no_redirect')) || empty($items[0]['value'])) {
    if (($items = field_get_items('node', $node, 'field_oa_media')) && count($items) == 1 && !empty($items[0]['uri']) && ($url = file_create_url($items[0]['uri']))) {
      return array('path' => $url);
    }
  }
  return node_uri($node);
}

/**
 * Implements hook_field_access().
 */
function aa_blog_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] == 'field_aa_blog_page_no_redirect' && !module_exists('oa_files')) {
    return FALSE;
  }
}

/**
 * Implements hook_oa_related_allowed_default().
 */
function aa_blog_oa_related_allowed_default() {
  return array('aa_blog_page');
}
